apiVersion: v1
kind: Secret
metadata:
    namespace: flask-application
    name: flask-secret
data:
    PGDB_USER: ENC[AES256_GCM,data:xKO6Pj6VpOuwmi0H,iv:Oxz7xlHsJ+MrYEYXP4t/6HCk3uFDiPGJnDcMlzbSHPA=,tag:jhQUSl+F1Iy0XR1sj1Wuiw==,type:str]
    PGDB_PASSWORD: ENC[AES256_GCM,data:1dXJOk+y4C/3AQUj,iv:JIOmvg6kTSB1T6yU6s8OVrvXdiVPUGcOR85/mnD97yQ=,tag:9UO+ssBEOD717n/VfIqUKA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/my-project-kubernates-436201/locations/northamerica-northeast1/keyRings/my-key-ring/cryptoKeys/my-key
          created_at: "2024-11-19T23:57:03Z"
          enc: CiQAxtRJI7JfSsKDY2QCV7KSsSXj3QDZRhYM+sT2PPmM6fJUTnQSSQBXz0frmZrZxbXUShZWp34ump6PAYKTu3MEwk1ySLq1U2OpkaxSYfNeOGlwcKOUBoTtsZ77jDDHbVbkTvZ61fWrsNbLSy/j9Xg=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T23:57:13Z"
    mac: ENC[AES256_GCM,data:o+5eF/BC1mqWOkYfTKlpIVm/B4LaPXR8413rhhzFR8jIvaIhKiE0bbe8waLSrxiNC+p7VUvIQEP5RbJ4FuOjswk14tZz4slU9ml3Bs/ZcKtbgACPC9IlR+Rv1i+PAV8GGdcLY/9v3TFagW9tz/ee4mIhwkRRZs3hVvG+DbAvaUg=,iv:edm3WH5/sGwJtK/mOblrT+MLVqUnvFSAOM8GbT6j2zs=,tag:YoNOY65yVZyFhgKcj9WUEA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
