apiVersion: v1
kind: ConfigMap
metadata: 
  name: postgres-config
  namespace: postgres-database
data:
  POSTGRES_DB: mydb
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postgres-database
  name: postgres-secret
data:  
  POSTGRES_USER: cG9zdGdyZXM= # Base64 encoded "postgres"
  POSTGRES_PASSWORD: cGFzc3dvcmQ= # Base64 encoded "password"
---
apiVersion: v1
kind: Pod
metadata:
  namespace: postgres-database
  name: postgres-pod
  labels:
    app: postgres-db
spec:
  containers:
  - name: postgres
    image: postgres:13
    env:
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_USER
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD
    - name: POSTGRES_DB
      valueFrom:
        configMapKeyRef:
          name: postgres-config
          key: POSTGRES_DB
    ports:
    - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: postgres-database
spec:
  selector:
    app: postgres-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
