apiVersion: v1
kind: Secret
metadata:
    namespace: postgres-database
    name: postgres-secret
data:
    POSTGRES_USER: ENC[AES256_GCM,data:z1j+2UjaPVeBX4L3,iv:ijTgUn0r+cV4ZMMs17yoL9IkSyNalURIIwrXZqTwiKQ=,tag:WBbIGKEKvllEgfNieZ+CAA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:5iA/zmZOatgo9IV1,iv:jZUJHfxTbXcNgUVkLl4yx3tYinQ42N9PBJijBWOdZDY=,tag:efvuogAHm1q0HLy14D4WIQ==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/my-project-kubernates-436201/locations/northamerica-northeast1/keyRings/my-key-ring/cryptoKeys/my-key
          created_at: "2024-11-19T23:55:58Z"
          enc: CiQAxtRJI9dONqJflWDCqEdw+4/VAP6yV4OS/F+K84tc7BO3+Z8SSQBXz0frzetcGb9u5dijzvopmq0QXYoMIuurbU0JA5Bvhn4FDmAb9X3G6PqGwf/4G4jQsBM6fcc9pW6d8pIbWj5M6lpzeqTMuW0=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T23:56:09Z"
    mac: ENC[AES256_GCM,data:sgx1qJIk48ZB/ihznz1bxqubxwpyzD68x+y9B5pWBLyzvoslg6tIEtMNQKiEuUSo0phuqLVXTk0ALPzgh6koQvqdNioIphzLcOBKljZUQklXpZYY8y4prCLfG9iwKAX1+90kiEX9UGtbZczFqpIrYZXJ1I11s8ZRb66rWa6zoI0=,iv:Mu9uKVrt0JlVlrVNf9rMb/UTW92WnGZlj0LPg1BMhTg=,tag:1lwtneRo+zv6VvxTn0cHmA==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
